Undo a change that broke qsim
Mindlessly fixing the complaint from pylint about the location of import
statements in qsimcirq/__init__.py was a bad idea. The imports have to
be at the bottom of this file or else at run-time, you get this cryptic
error:

```
 from . import qsim
  E   ImportError: cannot import name 'qsim' from partially initialized
  module 'qsimcirq' (most likely due to a circular import)
  (/tmp/tmp.hmte88Gw08/venv/lib/python3.10/site-packages/qsimcirq/__init__.py)
  =========================== short test summary info ============================
  ERROR ../../../project/qsimcirq_tests/qsimcirq_test.py
  !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
  =============================== 1 error in 2.12s ===============================
```